# Generated by Django 2.1.1 on 2019-02-07 13:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('staff_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LecturerSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('staff_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('adm_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=200)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Course')),
            ],
        ),
        migrations.CreateModel(
            name='UnitAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Course')),
                ('staff_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Lecturer')),
                ('unit_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='UnitDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('year', models.DateField()),
                ('unit_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='registeredunit',
            name='adm_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student'),
        ),
        migrations.AddField(
            model_name='registeredunit',
            name='unit_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Unit'),
        ),
        migrations.AddField(
            model_name='lecturersession',
            name='unit_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Unit'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=True, to='attendance.Department'),
        ),
        migrations.AddField(
            model_name='attendancelist',
            name='adm_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student'),
        ),
        migrations.AddField(
            model_name='attendancelist',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Course'),
        ),
        migrations.AddField(
            model_name='attendancelist',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.LecturerSession'),
        ),
        migrations.AddField(
            model_name='attendancelist',
            name='staff_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Lecturer'),
        ),
        migrations.AddField(
            model_name='attendancelist',
            name='unit_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Unit'),
        ),
    ]
